### ISSUE TITLE
Respond to Iteration and Release or Milestone Filtered pages

### ISSUE THREAD

**Issue by michiQ** [RallyCommunity/CustomChart#15]
This would be if the chart is placed on an iteration or release or Milestone filtered page, the data in the chart would also be filtered.

**Comment by krmorse** [comment]
Wow, oops!  Almost all of the code is already written to support this.  I just fat fingered a function name: https://github.com/RallyCommunity/CustomChart/blob/master/CustomChartApp.js#L183

I'll get a new version pushed out soon!

**Comment by krmorse** [comment]
Should be fixed now.  Please let me know if you're still having issues with it!

**Comment by michiQ** [comment]
Thank you!
