### ISSUE TITLE
Be able to aggregate by Task Estimates and Actuals

### ISSUE THREAD

**Issue by michiQ** [RallyCommunity/CustomChart#20]
Hey Kyle, would be great if we could have task estimates and actuals in the aggregation type box when we choose task as the type.  Thanks! Michiko

**Comment by krmorse** [comment]
Great idea!  This shouldn't be too much to implement I don't think...

**Comment by krmorse** [comment]
@michiQ, when you get a chance would you test this and see if it works for you?

https://github.com/RallyCommunity/CustomChart/blob/d218c5acb2bf9383d7fc88b4643bfd6d5c0fea6d/deploy/App-uncompressed.html

If you're satisfied with that I'll merge the PR...

**Comment by michiQ** [comment]
Hi Kyle!  Works great!  The only thing is that the filter doesn't work when I do a task chart, the filter isn't working.

**Comment by krmorse** [comment]
Hmm- I'll investigate.  I bet that's been broken forever and just nobody has tried to use it with tasks yet.  It's fun trying to make a generic app that works with every possible combination of things in our domain model!  Thanks for looking!

**Comment by krmorse** [comment]
Wow, that was a dumb defect... I tested this and everything seems to work better for me.  Give it a go again and let me know?  

https://github.com/RallyCommunity/CustomChart/blob/d43757ecd123f4b8cd43b8626ebeb0c9fe71eddc/deploy/App-uncompressed.html

**Comment by michiQ** [comment]
Thank you Kyle!! I'm literally training users on this app. Going so fast right now I can't even write cimm bye correctly!!  Thank you so much and I'll give it a whirl!! When is this moving to the app catalog!?

**Comment by michiQ** [comment]
lol comments (case in point)

**Comment by krmorse** [comment]
Hopefully in q3?  We're going to try to ship my last hackathon and add a whole community section to the catalog- wsjf, pi copy, release tracking board, etc.  All the most used apps on github...

**Comment by krmorse** [comment]
fixed in v1.0.2
