### ISSUE TITLE
Add support for ordering of selections

### ISSUE THREAD

**Issue by asradog** [RallyCommunity/CustomChart#23]
This would be helpful for such fields as Scheule State since they do not order in the way the States are actually run.  Same for the selections as they show on the Left hand list of the view.   I have attached a view where the lift hand column list of workspaces is alphabetical.  Would be great to be able to order.  Also the selection of Schedule State does not order the States as they would occur.   

![image](https://cloud.githubusercontent.com/assets/20404462/26217763/684e98ce-3bbd-11e7-90b0-0faec9bf7432.png)

![image](https://cloud.githubusercontent.com/assets/20404462/26217957/2b9c4f60-3bbe-11e7-83a6-5829eb901767.png)

**Comment by krmorse** [comment]
Hi, can you give a screenshot of your chart and/or further discuss how you have your settings configured so I can get a better idea of what this issue is about?  Thanks!

**Comment by asradog** [comment]
i added more details ...
thanks so much !

Sent thru space ...




On May 18, 2017, at 11:05 AM, krmorse <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, can you give a screenshot of your chart and/or further discuss how you have your settings configured so I can get a better idea of what this issue is about? Thanks!

**Comment by krmorse** [comment]
Great, thanks!  I actually just discovered this same issue this week and had a todo to look into it.  I'll keep you posted!

**Comment by krmorse** [comment]
I think I have this fixed.  Would you mind testing this code?  https://github.com/RallyCommunity/CustomChart/blob/916b317f7eef3de100f892a109061c8937f6131c/deploy/App-uncompressed.html

If you're happy with it I'll merge it.

**Comment by asradog** [comment]
that looks great for the Schedule State ordering ....
you're the best ... thanks so much !!!

Sent thru space ...




On May 18, 2017, at 8:21 PM, krmorse <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I have this fixed. Would you mind testing this code? https://github.com/RallyCommunity/CustomChart/blob/916b317f7eef3de100f892a109061c8937f6131c/deploy/App-uncompressed.html

If you're happy with it I'll merge it.

**Comment by krmorse** [comment]
fixed in 1.1.0
