### ISSUE TITLE
Aggregating by Date returns an Undefined Column

### ISSUE THREAD

**Issue by michiQ** [RallyCommunity/CustomChart#26]
Hey there Kyle, hope all is well!

I've found that when I try to aggregate by date:

![date2](https://user-images.githubusercontent.com/8203279/29132529-7d94f61a-7cfe-11e7-9bfd-a6d84dbff097.PNG)

I get a column that says 'undefined'

![date1](https://user-images.githubusercontent.com/8203279/29132548-8b27aff2-7cfe-11e7-8186-c7d97aaf36e1.PNG)

Thanks!
Michiko

**Comment by sficarrotta** [comment]
Would undefined be there for stories that had not been accepted?

—

Summer Ficarrotta, CSM
Principal Consultant, Presales - Agile Business Unit
1101 Haynes St Raleigh, NC 27604
719-964-2317 Mobile
summer.ficarrotta@ca.com
[nnamed]<https://www.rallydev.com/about/what-is-rally>

**Comment by michiQ** [comment]
Well - looks like it is aggregated by the accepted date but what I was hoping was to see a column for each date.  So I *do* have 29 stories accepted, but they are all in that 'undefined' column. 

![image](https://user-images.githubusercontent.com/8203279/29137163-5d40da0a-7d0d-11e7-9fc0-2ac4ce5016b5.png)

**Comment by krmorse** [comment]
Yep, this feels like a bug.  I bet it's not very hard to fix- probably just haven't done a whole lot of aggregating by date fields yet.  I'll keep you posted!

**Comment by krmorse** [comment]
@michiQ would you check out this fix?  

https://github.com/RallyCommunity/CustomChart/blob/c5c33efbd0d1c7de6d0a15f529e7edc3f3acf521/deploy/App-uncompressed.html

I have a pr all teed up and ready to merge if you're happy with the fix.  Right now it buckets them per day, formatted according to your datetime format settings.  Does that feel right?

**Comment by michiQ** [comment]
Yup I'll do this today

**Comment by michiQ** [comment]
WOOT!

![image](https://user-images.githubusercontent.com/8203279/29175402-f5a45b9c-7db6-11e7-8b0a-4201ae5aa309.png)

You Rock Kyle!! Thank yoU!

**Comment by krmorse** [comment]
Glad I could help.  That's a mighty colorful chart!  Neat idea though- you can kind of see the variability and rate of story acceptance throughout an iteration.

**Comment by krmorse** [comment]
Fixed in v1.1.1
