### ISSUE TITLE
Add the ability to group by month when aggregating by a date field

### ISSUE THREAD

**Issue by tmginzburg** [RallyCommunity/CustomChart#33]
For example, looking at defects, it would be great to aggregate by Creation Date and group by month, to see how many defects are created by month over time.

**Comment by krmorse** [comment]
@tmginzburg I think I got this working.  Jim Tykal was asking for something similar with test case results.  If you have some time can you kick the tires on the update?  (copy/paste the below html into a custom html app)

https://raw.githubusercontent.com/RallyCommunity/CustomChart/0867fea3dc4288feb49df76792ba72d3243c4622/deploy/App-uncompressed.html

If that looks right to you I'll merge #37 and get it updated in the community app catalog in the product!

**Comment by krmorse** [comment]
Fixed by #37 .  Implemented in v1.2.1
