### ISSUE TITLE
Filter + Query on owner and  {user} doesn't work

### ISSUE THREAD

**Issue by michael-jakobsen-dk** [RallyCommunity/CustomChart#34]
I'm trying to create a chart on my user stories by using the following query:

I've tried by query
(owner = {user})

and filter owner = "my name"

This doesn't however produce and user stories. The same query works find in a custom list on the same page.

If I user another user in the filtering it works fine!

**Comment by shapeles** [comment]
Ahh, apparently only on custom lists  - didn't know that.

![billede](https://user-images.githubusercontent.com/17159651/35972543-92bd1590-0cd2-11e8-86ff-08c87fbb313c.png)

**Comment by krmorse** [comment]
I'm going to reopen this since it's a nice feature request!

**Comment by krmorse** [comment]
I just merged a fix for supporting the {user} token in the query setting.  Let me know if it doesn't work for you!

**Comment by michael-jakobsen-dk** [comment]
Hi,
it doesn't work for me.

I'm using the following query (Owner = {user}) but it doesn't provide any results on the Chart, but 36 stories in a custom list.

I've just added the Chart from the app-selector, but I can't see whether it is the correct version - or I don't know how to.

BR
Michael
