### ISSUE TITLE
Add support for Risks

### ISSUE THREAD

**Issue by sficarrotta** [RallyCommunity/CustomChart#35]
I got all excited to see "Risk" as a Type, but then when I selected it the aggregate drop downs were incorrect

**Comment by krmorse** [comment]
Yep, this is a defect.  We'll need to publish a small update to sdk 2.1 to enable working with risks.  I agree there could be some useful charts to create with that new type!  @anagram15 ^^

**Comment by krmorse** [comment]
Fixed in version v1.2.2
