### ISSUE TITLE
Merge Custom Chart Code

### ISSUE THREAD

**Issue by sherimoore** [RallyCommunity/CustomChart#64]
Hi @krmorse  Can we get the Tech Services Version and the Community Version of this app so that we can take advantage of all the changes that are being made to the Community App?

**Comment by krmorse** [comment]
hey @sherimoore the community version is here: https://github.com/RallyCommunity/CustomChart
i'm not sure what the permissions look like for the tech services one, but the code is here: https://github.com/RallyTechServices/CustomChart <-- can you see that?

**Comment by sherimoore** [comment]
Hi @krmorse I am able to get to both of these versions of the Custom Chart.  I was hoping that the two versions could be merged in the community so that we don't lose out on any future updates that might happen in the community.  Amy said Tyr was going to merge the code before he left 😞

**Comment by krmorse** [comment]
Unfortunately, I'm not sure what all changes have been made to the tech services version of the app, and most likely the chart wouldn't be backwards compatible.  We wouldn't want to break a ton of existing customers' custom chart community apps.  

I'm also not sure what exactly this sort of work might even look like going forward in the new world of HCL.  In general Rally engineering has not done this sort of work...
